include:
  - 'https://gitlab.sib.fr/megalis/extraction-data-stack/raw/master/.docker-template.yml'

before_script:
  - wget https://gitlab.sib.fr/megalis/extraction-data-stack/raw/master/init.sh
  - source ./init.sh
  - export http_proxy=http://pro01.sib.fr:3128
  - export https_proxy=http://pro01.sib.fr:3128
  - export no_proxy=sib.fr
  - apk update && apk add sshpass openssh-client bash

stages:
  - build-angular
  - build
  - deploy

build angular app:
  before_script:
    - export http_proxy=http://pro01.sib.fr:3128
    - export https_proxy=http://pro01.sib.fr:3128
  image: node:16.13-buster
  stage: build-angular
  script:
    - npm install
    - npm run lint
    - |
      ./node_modules/.bin/ng build \
      --configuration=production \
      --aot \
      --output-path=dist/out/root

    # build pour deployer sur le path /marqueblanche-refonte
    - |
      ./node_modules/.bin/ng build \
      --configuration=production \
      --aot \
      --base-href=/marqueblanche-refonte/ \
      --output-path=dist/out/marqueblanche-refonte
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    expire_in: 15 mins
    paths:
      - dist/

docker image:
  extends: .build
  variables:
    IMAGE_NAME: "megalis/opendata/opendata-marqueblanche-refonte"

deploy dev:
  extends: .deployInteg
  variables:
    STACK_NAME: "marqueblanche-refonte"

deploy:
  extends: .deployPreProd
  variables:
    STACK_NAME: "marqueblanche-refonte"

deploy pre-prod-master:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "marqueblanche-refonte"

deploy prod:
  extends: .deployProd
  variables:
    STACK_NAME: "marqueblanche-refonte"
